name: Build and test

on:
  push:
    branches-ignore:
      - 'test-*'

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
  strategy:
    matrix:
      os: [macos-latest, ubuntu-latest]
  steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Compile
      shell: bash
      run: ./ci/build.sh
    - name: Run tests
      shell: bash
      run: ./build/runtests
